import { ItemPO } from '@/types';

export const randomData: ItemPO[] = [
   {
      id: 1,
      type: 'Kursi',
      name: 'Kursi A',
      variant: 'Merah',
      qty: 5,
      variantId: 1,
      itemId: 101,
      status: 'PROCESS',
      itemProgress: [
         {
            status: 'PROCESS',
            note: 'Sedang diproses',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang A',
      sales: 'Sales A',
      dateNote: '2023-09-02',
      dateDelivery: '2023-09-16',
   },
   {
      id: 2,
      type: 'Kursi',
      name: 'Kursi B',
      variant: 'Biru',
      qty: 10,
      variantId: 2,
      itemId: 102,
      status: 'FINISH',
      itemProgress: [
         {
            status: 'FINISH',
            note: 'Selesai produksi',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang B',
      sales: 'Sales B',
      dateNote: '2023-09-03',
      dateDelivery: '2023-09-17',
   },
   {
      id: 3,
      type: 'Meja',
      name: 'Meja X',
      variant: 'Coklat',
      qty: 8,
      variantId: 3,
      itemId: 103,
      status: 'PROCESS',
      itemProgress: [
         {
            status: 'PROCESS',
            note: 'Sedang diproses',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang A',
      sales: 'Sales A',
      dateNote: '2023-09-04',
      dateDelivery: '2023-09-18',
   },
   {
      id: 4,
      type: 'Meja',
      name: 'Meja Y',
      variant: 'Putih',
      qty: 6,
      variantId: 4,
      itemId: 104,
      status: 'FINISH',
      itemProgress: [
         {
            status: 'FINISH',
            note: 'Selesai produksi',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang B',
      sales: 'Sales B',
      dateNote: '2023-09-05',
      dateDelivery: '2023-09-19',
   },
   {
      id: 5,
      type: 'Lemari',
      name: 'Lemari Z',
      variant: 'Hitam',
      qty: 4,
      variantId: 5,
      itemId: 105,
      status: 'PROCESS',
      itemProgress: [
         {
            status: 'PROCESS',
            note: 'Sedang diproses',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang A',
      sales: 'Sales A',
      dateNote: '2023-09-06',
      dateDelivery: '2023-09-20',
   },
   {
      id: 6,
      type: 'Lemari',
      name: 'Lemari W',
      variant: 'Putih',
      qty: 7,
      variantId: 6,
      itemId: 106,
      status: 'FINISH',
      itemProgress: [
         {
            status: 'FINISH',
            note: 'Selesai produksi',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang B',
      sales: 'Sales B',
      dateNote: '2023-09-07',
      dateDelivery: '2023-09-21',
   },
   {
      id: 7,
      type: 'Rak',
      name: 'Rak K',
      variant: 'Kayu',
      qty: 3,
      variantId: 7,
      itemId: 107,
      status: 'PROCESS',
      itemProgress: [
         {
            status: 'PROCESS',
            note: 'Sedang diproses',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang A',
      sales: 'Sales A',
      dateNote: '2023-09-08',
      dateDelivery: '2023-09-22',
   },
   {
      id: 8,
      type: 'Rak',
      name: 'Rak M',
      variant: 'Metal',
      qty: 9,
      variantId: 8,
      itemId: 108,
      status: 'FINISH',
      itemProgress: [
         {
            status: 'FINISH',
            note: 'Selesai produksi',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang B',
      sales: 'Sales B',
      dateNote: '2023-09-09',
      dateDelivery: '2023-09-23',
   },
   {
      id: 9,
      type: 'Sofa',
      name: 'Sofa L',
      variant: 'Kulit',
      qty: 2,
      variantId: 9,
      itemId: 109,
      status: 'PROCESS',
      itemProgress: [
         {
            status: 'PROCESS',
            note: 'Sedang diproses',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang A',
      sales: 'Sales A',
      dateNote: '2023-09-10',
      dateDelivery: '2023-09-24',
   },
   {
      id: 10,
      type: 'Sofa',
      name: 'Sofa P',
      variant: 'Kain',
      qty: 1,
      variantId: 10,
      itemId: 110,
      status: 'FINISH',
      itemProgress: [
         {
            status: 'FINISH',
            note: 'Selesai produksi',
            timestamp: 1688718768,
            user: {
               name: 'Admin',
            },
         },
      ],
      store: 'Gudang B',
      sales: 'Sales B',
      dateNote: '2023-09-11',
      dateDelivery: '2023-09-25',
   },
   // Data tambahan lainnya sesuai kebutuhan Anda
];
